# Generated by Django 4.2.6 on 2023-10-31 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pacote',
            name='recurso',
        ),
        migrations.AddField(
            model_name='pacote',
            name='recursos',
            field=models.ManyToManyField(to='core.recurso', verbose_name='Recursos'),
        ),
    ]
